server:
  port: 8000

spring:
  application:
    name: product_sky
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/the_sky?serverTimezone=GMT%2B8
    username: root
    password: root


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/
    ###需要将我得服务注册到eureka上
    register-with-eureka: true
    ###需要检索这个服务
    fetch-registry: true

